import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Button from "../components/Button";
import Heading from "../components/Heading";
import UserOccasions from "../components/UserOccasions";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: sessionData } = useSession()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {sessionData
        ? <>
          <Heading>
            Your Occasions
          </Heading>
          <UserOccasions />
          <div>
            <Link href="occasions/add">
              <Button>New occasion</Button>
            </Link>
          </div>
        </>
        : <>
          <Heading>
            Welcome!
          </Heading>
          <div>
            Sign in to create and see your occasions
          </div>
        </>}
    </>
  );
};

export default Home;
