import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Button from "../components/Button";
import Heading from "../components/Heading";
import UserOccasions from "../components/UserOccasions";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: sessionData } = useSession()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
        <Heading>
          Christmas Bingo
        </Heading>
        {sessionData
          ? <>
            <UserOccasions />
            <div>
              <Link href="add">
                <Button>New occasion</Button>
              </Link>
            </div>
          </>
          : <div>
            Sign in to see your occasions
          </div>}
      </div>
    </>
  );
};

export default Home;
