import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";
import Button from "../components/Button";
import { FiPlus } from 'react-icons/fi'
import Heading from "../components/Heading";

const Home: NextPage = () => {
  const utils = trpc.useContext()
  const events = trpc.event.getAll.useQuery()
  const mutation = trpc.event.addInstance.useMutation({
    onSuccess: () => utils.event.getAll.invalidate()
  })

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
        <Heading>
          Christmas Bingo
        </Heading>
        {events.data && events.data.length === 0 && <div>So empty :(</div>}
        {events.data && events.data.length > 0 && <ul className="max-w-md w-full text-white space-y-2">
          {events.data.map((event) => <li key={event.id} className="grid grid-cols-[2ch_1fr_auto] gap-2 items-center">
            <div>
              {event._count.EventInstance}
            </div>
            <div>
              <Link href={`events/${event.id}`}>
                {event.text}
              </Link>
            </div>
            <Button round onClick={() => mutation.mutate({ eventId: event.id })}>
              <FiPlus />
            </Button>
          </li>)}
        </ul>}
        <div>
          <Link href="add">
            <Button>New event</Button>
          </Link>
        </div>
      </div>
    </>
  );
};

export default Home;
